### ISSUE TITLE
[GUI] Responsivity

### ISSUE THREAD

**Issue by ivan-ristovic** [MATF-Software-Verification/2020_05_Massif_Visual#2]
## Issue description
Situations like the ones shown in the image below can arise where you do not see the snapshots list completely. I noticed that the width of the snapshots tab changes when loading different massif files but it is only affected by the top-most buttons (since child buttons are indented, part of their text might go out of bounds).

Rescaling the UI does not change the width of the snapshots tab, just the graph width.

![1](https://user-images.githubusercontent.com/19779112/115110352-51f90480-9f7b-11eb-97f7-3971066b6e39.PNG)

## Proposed changes
Make GUI more responsive, or atleast the snapshots list width should be expanded to the width of child buttons. 

## Additional points
Perhaps the UI width should increase the width of the snapshots tab as well (not only the graph tab)?

**Comment by aleksandraniksic** [comment]
Commit accidentally attached to this issue.

**Comment by PetarZecevic97** [comment]
We came to a conclusion that horizontal scroller is the best solution. If we dynamically change the width of list of snapshots based on number of indentations, the width can become inconveniently big.
Also dynamically changing the width is problematic and difficult.
Is that okay?

**Comment by ivan-ristovic** [comment]
Sure, it is probably the best solution anyway.
