### ISSUE TITLE
[GUI] Clear recent files keeps menu items

### ISSUE THREAD

**Issue by ivan-ristovic** [MATF-Software-Verification/2020_05_Massif_Visual#3]
## Issue description
Clearing recent files will not remove the entries from the dropdown list. This behaviour is persisted until application restart.

![image](https://user-images.githubusercontent.com/19779112/115110444-c338b780-9f7b-11eb-8399-90a53fc7969e.png)

## Proposed changes
Perhaps include [QMenu::clear()](https://doc.qt.io/qt-5/qmenu.html#clear) or [QMenu::remove*()](https://doc.qt.io/qt-5/qwidget.html#removeAction()) call(s) when clearing menus.

**Comment by AleksandarTheBoulderRankovic** [comment]
We fixed this issue by changing the visibility property of actions :rocket:
