### ISSUE TITLE
[Exec] Program execution feedback

### ISSUE THREAD

**Issue by ivan-ristovic** [MATF-Software-Verification/2020_05_Massif_Visual#4]
## Issue description
Create a simple program which segfaults, and try to invoke it:
```c
int main() {
    int *x = NULL;
    printf("%d", *x);
}
```

Since massif file is generated without snapshots, the graph is empty. However, the program did not execute normally (exit code is not `0`). For more complex programs, there could be multiple snapshots but due to segfaults late in application execution we will have no way to know if the application has exited normally.

Furthermore, if the program is running for long periods of time (which is expectable since valgrind's instrumentation could add an overhead of ~30x), there is no information in the UI regarding the program's execution state.

## Proposed changes
- Upon executing a program in a different thread, spawn a popup window which shows the current state, for example `Executing...`, (perhaps with elapsed time?)
- After the program has exited, check it's exit code on completion. Update the popup with information about exit code and/or stdout/stderr if it was not `0`, otherwise destroy the window (or keep the runtime statistic?)

**Comment by aleksandraniksic** [comment]
When the thread starts running popup window shows up saying "Executing...". After the thread is finished, if exit code is equal to 0, then the window closes, otherwise duration of execution and exit code are displayed in the window.
