### ISSUE TITLE
[Parser] Invalid massif files

### ISSUE THREAD

**Issue by ivan-ristovic** [MATF-Software-Verification/2020_05_Massif_Visual#5]
What is the current parser behaviour on invalid input? I attempted to load a junk massif file and it looks something like this:
![image](https://user-images.githubusercontent.com/19779112/115111631-7952d000-9f81-11eb-8668-0626b56981dc.png)

Since we are expecting massif file format, it seems to me that it is possible to detect invalid files while parsing?

**Comment by mandja96** [comment]
We think we covered most of the invalid inputs. The current (after issue fixing) parser behaviour on invalid input is not opening a new tab at all, and displaying a helpful message 🐿️.
